### ISSUE TITLE
doesn't boot (225)

### ISSUE THREAD

**Issue by BigButt** [agajews/ApricityOS#12]
Installation works fine but when I reboot I'm getting:
'start version 225'
And there it stops.

**Comment by Glanzer** [comment]
I've got the same problem too.
After some time it complains about systemd not being able to initialize the virtual console.

**Comment by agajews** [comment]
Did you install Apricity using one of the two automated partitioning methods, or did you use the advanced partitioner? Also, are you using a UEFI installation, or are you using Legacy Boot? Using your responses from each of these two questions, I would recommend that you retry the installation using the other option, i.e. UEFI instead of Legacy Boot, an automated partitioning scheme instead of an advanced one, or vice-versa.

**Comment by agajews** [comment]
Also, what happens if you boot from your live-usb again, close the instance of the installer that opens automatically, open a terminal and run "sudo sed -i 's/- hardwarecfg/#- hardwarecfg/g' /usr/share/calamares/settings.conf", then open the installer again and run the installation? Also keep in mind that the installer must format a fat32 /boot/efi partition when booting with UEFI, and that under legacy boot, formatting a /boot partition is recommended.

**Comment by BigButt** [comment]
Yes, I used the automated install method. Didn't partition myself.
No, I've got no UEFI. My Computer is about 6 years old.
Will test the installer thingy later.

**Comment by Fepame** [comment]
Same problemas here

**Comment by agajews** [comment]
This seems to be a bug with Legacy Boot + Plymouth. Does the gray loading circle appear? If so, what happens if you hit escape while the gray circle loader is spinning?

**Comment by Fepame** [comment]
The gray circle appears when I hit escape, the o.s starts normally.

**Comment by agajews** [comment]
I'm glad that it worked, but it really is something important that we should fix. Maybe we'll release a September Beta 2 during the second half of this month if we figure out how to get Plymouth and Legacy Boot to play nicely.

**Comment by BigButt** [comment]
The escape workaround doesn't work for me.

**Comment by BigButt** [comment]
Strange thing. It started, not because of pushing escape.  I didn't hit any key. Usually I press return at grub. That does the trick for me.

**Comment by agajews** [comment]
And what pressing 'e' while grub is presenting boot options then removing 'quiet, splash'?

**Comment by Glanzer** [comment]
I'm sorry, I've got working ttys without login, and therefore concluded, that it wasn't with the boot process, bot some step further in.

I tried both, a custom setup with a huge swap and a extra partition for /usr, and a 'automated' install that uses the whole disk (and creates a tiny swap partition). Both (should) boot via MBR, since the device isn't the newest.

The setup-thumbdrive worked without problems, although it can to get stuck on the 'grey loading screen' mentioned above. (I ignored that one since it happens with other distribution's live disks as well, and is most certainly a mechanical problem with the thumbdrive - as I said, the device is quite old, and got it's share of wear and tear)


If I were  to guess, I'd suspect something wrong with systemd, but I haven't had time to check it since my post above.

**Comment by agajews** [comment]
Does systemd throw any errors while it's booting?

**Comment by Glanzer** [comment]
not consistently. I've got a systemd related message once, but did not write it down, since I suspected to come across it again. Anyway - I'm going to chroot into the system later, and check it's settings. I'll keep you posted.

**Comment by Glanzer** [comment]
Short update - hitting Ctrl+C or Ctrl+D while the error is on screen, I finally gets an output.
In essence:

<code>
Kernel panic - not syncing: Attempted to kill init! exitcode=0x00000000

WARNING: CPU: 0 PID: 1 at arch/x86/kernel/smp.c:124 native_smp_send_reschedule+0x61/0x70()
</code>

After which he seems to list all the other modules that don't work as a result.
Could I be having a problem with my 4 year old Intel Atom?

**Comment by agajews** [comment]
It could be, although it's unlikely since you got to the live image just fine. It could be a graphics thing, since some graphics settings do change between the live image and the installed os.

**Comment by gamernorbi** [comment]
Same issue

**Comment by Glanzer** [comment]
In case nobody did find out yet - I might have a solution.

I solved the whole shebang by chrooting into my install, using arch-chroot (after installing arch-install-scripts via pacman onto the live-disk), and running
<code>$> mkinitcpio -p linux</code>
inside.
Weirdly a installation step, that broke my regular arch-installations until I started skipping it.
https://bbs.archlinux.org/viewtopic.php?id=202301

**Comment by Glanzer** [comment]
short addition - I tried to put it on my old production machine (Intel i4, Nvidia GT 640, nothing fancy), which resulted in the live-environment, turning all connected screens off after the 'grey screen' phase, so there might be more going wrong here.

On a sidenote, I wonder how much of all the above problems (aside from running the live-environment) could be solved by running a regular arch-installation with a modified packagelist for pacstrap.

**Comment by agajews** [comment]
I do believe this is a driver issue. The September beta doesn't include the required driver for that card, but we'll be sure to include it in the next release. I'll let you know when we have an alpha available if you want so that you can make sure we actually do add the correct driver.

**Comment by Glanzer** [comment]
Absolutely - I'd really like that.

**Comment by agajews** [comment]
Just wanted to let everyone here know that we've quietly pushed a new iso that may fix this problem to the Apricity OS website (note that the new filename is apricityos_09.2015-beta2.iso, so if the download button doesn't link to a file with that name, reload the Apricity site and/or clear your browser cache).

**Comment by Glanzer** [comment]
Yeah, that solved it on my end.

**Comment by agajews** [comment]
Great!
