### ISSUE TITLE
Default icon size = huge

### ISSUE THREAD

**Issue by lunemec** [agajews/ApricityOS#7]
Hi,

love the new beta, it works flawlessly now! However, the default desktop icons are kind of huge. Also I can't find a way to change this in GUI and I don't know which program is handling this to look for configs ...

Maybe set default a bit smaller? ...

Thx

**Comment by agajews** [comment]
It's actually really easy. Just open files, click "Files" in the menu bar at the top of your screen, select "Preferences", then under the "Views" tab change "Icon View Defaults" from "Standard" to "Small". I originally thought you were talking about the app grid icons and wrote you an application to get around a bug in GNOME and set them to a more reasonable size. If you think those icons are also too big by default, you can install apricity-gridmod from Pamac.

**Comment by rjslinux** [comment]
Don't really want to open a new bug for this since it is the apricity-gridmod app that seems to be causing the issue.

I am running apricity on an Acer AS5750 laptop and when I install the apricity-gridmod I loose the ability to control the volume and brightness with the function keys once I log in and the script loads. Once I remove the .firstrun.ran file from the home directory and remove the apricity-gridmod, run firstrun.sh and log out and back in the keys work properly.

By the way, love the OS - great job

**Comment by agajews** [comment]
Gridmod is a very hacky solution to an unfortunate lack of customizability of several aspects of Gnome. It used to be that the Gnome JavaScript files were open and changeable, but starting in 3.8, they turned off that great feature and as a result gridmod has to do a lot of work with the inner workings of Gnome, something that inevitably causes unexpected problems.

**Comment by rjslinux** [comment]
I agree, I was just making sure to report it in case another person came across the issue.

Not complaining, just pointing out a solution to a possible issue.
